version: '3.8'
services:
  nats-server:
    restart: always
    image: nats:latest
    ports:
      - '4222:4222'
      - '8222:8222'
    command: '--jetstream --store_dir /data/jetstream'
    volumes:
      - nats-data:/data
volumes:
    nats-data:
        driver: local
networks:
  default:
    name: ${DEV_NETWORK_NAME}
    external: true
