version: '3'
services:
  sight-miner-backend:
    environment:
      - NODE_CODE=03mjqcshj
      - GATEWAY_API_URL=http://host.docker.internal:8718
      - GATEWAY_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIweDJhRTk0NjRGMURmNTQ2OTNkOWJFZTQwMzhjZjE1QUE1QTEyOTlDNDAiLCJpc3MiOiJodHRwczovL3NpZ2h0YWkuaW8iLCJhdWQiOiJodHRwczovL3NpZ2h0YWkuaW8iLCJhZGRyZXNzIjoiMHgyYUU5NDY0RjFEZjU0NjkzZDliRWU0MDM4Y2YxNUFBNUExMjk5QzQwIiwiaWF0IjoxNzQyODI0MzE3LCJleHAiOjE3NDU0MTYzMTd9.9B3Q3v_Q1LU9adhP7kdP-fwvUEprb3jHtwLPYaSvpTs
      - GPU_BRAND="NVIDIA"
      - DEVICE_TYPE="Linux"
      - GPU_MODEL="NVIDIA GeForce RTX 3050 Laptop GPU"
      - OPENAI_API_KEY=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
      - OPENPIPE_API_KEY=opk_a7d820895a6f138af785be1b36837d59904aed2f39
      - PRIVATE_KEY=0xee9f59011a865e83108a58b954b9df506c8a975afe9af6f8e28df3a089f90972
