services:
  sight-miner-backend:
    build:
      context: ${BACKEND_PATH} 
      dockerfile: Dockerfile 
    ports:
      - "8716:8716"
    environment:
      - NODE_ENV=development
    env_file:
      - ${BACKEND_PATH}/.env
    volumes:
      - .:/app
      - postgres-data:/var/lib/postgresql/data
      - ${SQL_SCRIPT_PATH}
    networks:
      - app-network


  sight-miner-frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=development
    env_file:
      - ${FRONTEND_PATH}/.env
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:15.5-alpine
    container_name: postgres-db
    ports:
      - "7543:5432"
    environment:
      - POSTGRES_DB=saito_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      -  ${SQL_SCRIPT_PATH}:/docker-entrypoint-initdb.d/1741604050_up.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  ollama_data:
    driver: local
