version: '3'

services:
  sight-miner-backend:
    image: gcr.io/celtic-descent-398803/sight-miner-backend:0.0.2-SNAPSHOT
    ports:
      - "8716:8716"
    networks:
      - app-network

  sight-miner-frontend:
    image: gcr.io/celtic-descent-398803/sight-miner-frontend:0.0.2-SNAPSHOT
    ports:
      - "3000:3000"
    networks:
      - app-network

  sight-miner-postgres:
    image: gcr.io/celtic-descent-398803/sight-miner-postgres:0.0.1-SNAPSHOT
    container_name: postgres-db
    ports:
      - "7543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local