version: '3'
services:
  sight-miner-backend:
    environment:
      - NODE_CODE=default
      - GATEWAY_API_URL=https://sightai.io
      - GATEWAY_API_KEY=default
      - REWARD_ADDRESS=default
      - GPU_BRAND="NVIDIA"
      - DEVICE_TYPE="Linux"
      - GPU_MODEL="NVIDIA GeForce RTX 4060 Laptop GPU"
